"""
Curated few-shot examples for Java test generation.

Each module contains gold-standard test examples for a specific component type.
"""

from .entity_basic import ENTITY_BASIC_EXAMPLE, ENTITY_BASIC_META
from .entity_collections import ENTITY_COLLECTIONS_EXAMPLE, ENTITY_COLLECTIONS_META
from .controller_pagination import CONTROLLER_PAGINATION_EXAMPLE, CONTROLLER_PAGINATION_META
from .controller_exception import CONTROLLER_EXCEPTION_EXAMPLE, CONTROLLER_EXCEPTION_META
from .validator_fields import VALIDATOR_EXAMPLE, VALIDATOR_META
from .formatter_parse import FORMATTER_EXAMPLE, FORMATTER_META
from .service_repository import SERVICE_REPOSITORY_EXAMPLE, SERVICE_REPOSITORY_META

__all__ = [
    "ENTITY_BASIC_EXAMPLE", "ENTITY_BASIC_META",
    "ENTITY_COLLECTIONS_EXAMPLE", "ENTITY_COLLECTIONS_META",
    "CONTROLLER_PAGINATION_EXAMPLE", "CONTROLLER_PAGINATION_META",
    "CONTROLLER_EXCEPTION_EXAMPLE", "CONTROLLER_EXCEPTION_META",
    "VALIDATOR_EXAMPLE", "VALIDATOR_META",
    "FORMATTER_EXAMPLE", "FORMATTER_META",
    "SERVICE_REPOSITORY_EXAMPLE", "SERVICE_REPOSITORY_META",
]
